### PR TITLE
Tnbt21 recent shoutouts testing

### PR DESCRIPTION
**Pull request by nkhorvash**
This will add testing for the header and shoutout card components. Please give feedback on whether the tests seem appropriate.

### CODE REVIEW

**Comment by Incarnate-Infinity** [comment]
A couple of notes: you don't need any of the imports from @jest/globals, the things imported should be present by default. You can remove those imports and the tests will still run just fine (or at least they should, they run fine for me).

Additionally, I'd lean towards "___.test.ts" for your file names, to better indicate which file the testing file is associated with. Jest should pick them up either way so this one isn't particularly important.

Fun fact along those lines: I believe "test" as you're using in some of your tests and "it" as I'm using in mine operate the same, and are just there to make the test setup and name read more like an english sentence. I don't think that change is super important, but it could be good for us to pick one or the other for consistency's sake.

**Comment by nkhorvash** [comment]
@Incarnate-Infinity thanks for the feedback, I've applied all 3 changes. I agree, it's a good idea to be consistent with things like filenames and using it instead of test for overall readability.

**Comment by Incarnate-Infinity** [comment]
LGTM 👍

**Comment by lsanchezcode** [comment]
LGTM! :)

**Pull request merged**
