### PR TITLE
Tnbt1 view recent shoutouts

### PR DESCRIPTION
**Pull request by nkhorvash**

### CODE REVIEW

**Comment by Incarnate-Infinity** [comment]
This feature's looking fine for me, I'll give it my approval

**Comment by Incarnate-Infinity** [comment]
LGTM 👍

**Comment by lsanchezcode** [comment]
Hello! I think this is where I am supposed to put notes, but I so not remember! Overall things look good! The only thing I can say is that be sure to update your README if you need to to be sure that people will know how to actually run the project such as running npm install @auth0/nextjs-auth0 in the terminal before running or any sort of things like those!

**Comment by Incarnate-Infinity** [comment]
@lsanchezcode @nkhorvash 
> Hello! I think this is where I am supposed to put notes, but I so not remember! Overall things look good! The only thing I can say is that be sure to update your README if you need to to be sure that people will know how to actually run the project such as running npm install @auth0/nextjs-auth0 in the terminal before running or any sort of things like those!

As a note, adjust from "npm install" to "yarn add" since we're using yarn as our package manager for this project rather than npm, and we don't want two -lock files to wind up running around!

**Comment by nkhorvash** [comment]
The `yarn install` command in the readme should handle all dependencies being used in the `package.json`, but good point, I will see if the readme needs any additions.

**Comment by nkhorvash** [comment]
Good catch! It must have been cached from a working version, because there was no issue on my local. I fixed the filename and checked the reference.

**Comment by Incarnate-Infinity** [comment]
LGTM 👍

**Pull request merged**
