### PR TITLE
Tnbt5 proxy api search

### PR DESCRIPTION
**Pull request by Incarnate-Infinity**
Allows for searching through profiles by name, email, or both.

Due to the way our proxy api works and is set up, there's no ability to actually reach out to the proxy api in a more direct way. Currently proving it with reading through the logic, and with jest tests. If there are more paths worth considering testing, let me know.

Addl note, no current setup for testing the "truncate to 100" portion due to the size of the mocks. Tests could be produced for this, but would require the creation of a whole lot of additional mocks to get our profile data up past 100 entries. Can be done if we'd like to have that for the confirmation of functionality though.
@nkhorvash @lsanchezcode

### CODE REVIEW

**Comment by nkhorvash** [comment]
In search.ts there is a `console.log` on line 22, is that meant to be left in?

**Comment by Incarnate-Infinity** [comment]
> @Incarnate-Infinity In search.ts there is a `console.log` on line 22, is that meant to be left in?

That is not! I had that to try and see if I could figure out where the raw query string lived (if anywhere) to try and use that instead of stitching it together. I did not find anything, so wound up with the implementation seen there. Good catch! I've removed that console log statement.

**Comment by nkhorvash** [comment]
LGTM 👍🏼

**Comment by lsanchezcode** [comment]
LGTM!!! :)

**Pull request merged**
